[workspace]
members = [
    "brass-aphid-wire-messages", 
    "brass-aphid-wire-decryption",
    "brass-aphid-wire-macros",
    "brass-aphid-wire-messages/fuzz", "capability-compendium",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
